# Generated by Django 5.1.2 on 2024-11-03 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='dni_cliente',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
